# YouTube Data API v3 key
# Get one from Google Cloud Console
youtube-data-api-key: abc123

enable-tab-theater-list: true

video-storage:
  mysql:
    use: false
    host: localhost
    port: 3306
    database: cinemamod
    username: root
    password: password
  sqlite:
    use: true

# Theater types:
#   public - Allows anyone to request videos, has no theater owner
#   private - Has a theater owner, they can lock the video queue, force skip, etc
#   static - Has no theater owner, only plays a single video defined in this config
#   static.url
#   static.res-width
#   static.res-height

theaters:
  theater1:
    name: Theater 1
    hidden: false # should the theater be shown in tab?
    type: public
    screen:
      world: world
      x: 0
      y: 8
      z: 0
      facing: SOUTH
      width: 6
      height: 3
      visible: true # should the screen be invisible? (for audio only theaters)
      muted: false # should the screen always be muted?
    preview-screens:
      preview1:
        world: world
        x: 5
        y: 8
        z: 5
        facing: NORTH
  theater2:
    name: PATRIOT THEATER (static)
    hidden: false
    type: static
    screen:
      world: world
      x: 50
      y: 5
      z: 50
      facing: SOUTH
      width: 9
      height: 1
      visible: true
      muted: true
    static:
      url: 'https://www.youtube.com/watch?v=w5x_9KEogM8'
  theater3:
    name: Theater 3 (private)
    hidden: true
    type: private
    screen:
      world: world
      x: 100
      y: 5
      z: 100
      facing: SOUTH
      width: 1
      height: 1
      visible: true
      muted: false

# automatically makes 200x200x64 regions for testing when an existing region is not found
autogenCubicRegions: true